domain: 'localhost'

admin:
  enable: true
  auth: true

jwt:
  signing-key: 'gingo'
  expires-time: 604800000
  buffer-time: 86400000
  issuer: 'gingo'

mysql:
  path: 'localhost' # 服务器地址
  port: '3306' # :端口
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'comback'
  username: 'root'
  password: 'root'
  prefix: "t_" # 全局表前缀，单独定义 TableName 则不生效
  singular: false # 是否开启全局禁用复数，true表示不开启，false表示所有表明均单数
  engine: "" # 引擎，默认InnoDB
  max-idle-conns: 10 # 空闲中的最大连接数
  max-open-conns: 100 # 打开到数据库的最大连接数
  log-mode: true # 是否开启Gorm全局日志
  log-zap: false # 是否通过zap写入日志文件

zap: # 日志配置
  level: info # 日志级别
  prefix: '[east_white_common_admin/server]' # 日志前缀
  format: console # 输出
  director: log # 日志存放的文件
  encode_level: LowercaseColorLevelEncoder # 编码级别
  stacktrace_key: stacktrace # 栈名
  max_age: 0 # 日志留存时间
  show_line: true # 显示行
  log_in_console: true # 输出控制台
